### PR TITLE
Updated GitRepositories and Versions

### LINKED ISSUE #51: Source for orc from pkg-gstreamer has been moved
The `anonscm.debian.org` has been discontinued. The `converter/get-sources.sh` script cannot download the `orc` package. I found that one has to change line 49 
```
(cd $SRCDIR; git clone git://anonscm.debian.org/pkg-gstreamer/orc.git orc; cd orc; git checkout "$ORC_VER")
```
to
```
(cd $SRCDIR; git clone https://salsa.debian.org/gstreamer-team/orc.git orc; cd orc; git checkout "$ORC_VER")
```

### PR DESCRIPTION
**Pull request by callmenemo491**
Updated many git repository links and updated the versions to the 'latest'

this will solve/ close #51 
and also includes: the PR code of:  #44

@mi-g , are you able to merge this pull request into the code.
(note there are several issue tickets, i think you can close also...)

### CODE REVIEW

**Comment by mettacrawler** [comment]
This still has issues:
```
(cd $SRCDIR; git clone https://foo; cd foo; git checkout "$FOO_VER")
```

If git clone fails, cd will fail too but "git checkout" will not fail and it will change the branch that the main git is on.

It should not use ; as the command separator. It should use && to avoid running commands if there is a failure in a previous command.
```
(cd $SRCDIR && git clone https://foo && cd foo && git checkout "$FOO_VER")
```

**Comment by callmenemo491** [comment]
@mettacrawler , thanks for the info., you are correct - so i have taken the feedback and updated the PR.

**Comment by mettacrawler** [comment]
Is the converter even a requirement? It appears to me that is just ffmpeg, ffprobe and ffplay and the shared libraries to run those.

When I look at https://aur.archlinux.org/packages/vdhcoapp/ it makes no attempt to download the converter source code.  It just uses the Arch Linux ffmpeg package as-is and it runs just fine that way.

I think it's more important to pay attention to node js dubnium LTS going EOL on April 30, 2021.  That and `found 23 vulnerabilities (7 low, 6 moderate, 10 high)` and also `21 packages are looking for funding`

**Review by mi-g — APPROVED** [review]
Thanks for the PR !

**Pull request merged**
